### ISSUE TITLE
请教下流程图选型问题

### ISSUE THREAD

**Issue by lk0606** [mizuhokaga/jsplumb-dataLineage#2]
请问下为什么选择了jsplumb这个库，而不是选择antv-x6，因为官方的jsplumb开源资料、demo比较少。
而antv-x6文档和生态相对完善。

**Comment by mizuhokaga** [comment]
因为当时的需求是为公司平台前端(vue2)快速添加流程图展示功能,作为非专业前端,看到jsplumb觉得简单就做了...
从现在的视角看,jsplumb社区版的确对开发不够友好

**Comment by lk0606** [comment]
> 因为当时的需求是为公司平台前端(vue2)快速添加流程图展示功能,作为非专业前端,看到jsplumb觉得简单就做了... 从现在的视角看,jsplumb社区版的确对开发不够友好

如果以现在来看的话，新项目，直接使用antv-x6是否会更好，你怎么看

**Comment by mizuhokaga** [comment]
> > 因为当时的需求是为公司平台前端(vue2)快速添加流程图展示功能,作为非专业前端,看到jsplumb觉得简单就做了... 从现在的视角看,jsplumb社区版的确对开发不够友好
> 
> 如果以现在来看的话，新项目，直接使用antv-x6是否会更好，你怎么看

新项目当然antv-x6,在发布本repo的几年里,我收到的反馈有:
1. 节点数量为三位数甚至更多时渲染效率不高
2. 渲染后想修改指向比较繁琐等等
3. 小地图feature何时添加

大部分情况我都很难解决,antv-x6既有文档又有demo,何乐而不为?
